#!/bin/bash

#python2 -m pip install ipykernel
echo "begin postbuild"
#wget https://bootstrap.pypa.io/get-pip.py
#python2 get-pip.py
#which pip2.7
pwd
ls
#conda create -n qiime -c bioconda qiime
#pip install bash_kernel
#python -m bash_kernel.install
wget https://raw.githubusercontent.com/andrew-leith/jupyterhub-test1234/master/environment.yml

echo "end postbuild"
